### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by g19i85g**

### CODE REVIEW

**Comment by borodulin** [comment]
Fix generate WSDL 
-                            $this->processType(str_replace('\','/',$matches[1])),
-                            $this->processType($matches[1]),
  Why? Can you set an example to reproduce the problem?

**Comment by borodulin** [comment]
Fix Yii::autoload() fails if the class was included before.
Can you set an example?

**Comment by borodulin** [comment]
Improvements - a good idea. However, fixes and improvements to better divide in the different pull requests to be able to merge each separately. All the crowd is difficult to check, and some things may require clarification and discussion.

**Comment by g19i85g** [comment]
Fix generate WSDL

$this->processType(str_replace('\','/',$matches[1])),
$this->processType($matches[1])

``` php
<?php

use conquer\services\WsdlGenerator;
use yii\web\Controller;

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

class TestController extends Controller
{
    /**
     * @param TestA $test
     * @soap
     */
    public function test($test)
    {
    }
}

class TestA
{
    /**
     * @var string
     * @soap
     */
    public $property1;
    /**
     * @var \yii\helpers\ArrayHelper
     * @soap
     */
    public $property2;
}

$generator = new WsdlGenerator();
$generator->bindingStyle = WsdlGenerator::STYLE_DOCUMENT;
$wsdl = $generator->generateWsdl(TestController::className(), '');
```

caused:
Fatal error: Uncaught exception 'ReflectionException' with message 'Class /yii/helpers/ArrayHelper does not exist' in /app/vendor/conquer/services/WsdlGenerator.php on line 383

**Comment by g19i85g** [comment]
Fix Yii::autoload() fails if the class was included before.

``` php
Yii::autoload(ArrayHelper::class);
Yii::autoload(ArrayHelper::class);
```

caused:
Cannot redeclare class yii\helpers\ArrayHelper in /app/vendor/yiisoft/yii2/helpers/ArrayHelper.php

**Comment by g19i85g** [comment]
"However, fixes and improvements to better divide in the different pull requests to be able to merge each separately."
Ok i make it next time.

**Comment by borodulin** [comment]
Ok, bugs confirmed. If you will make separate pull request for them, I will merge it immediatly. But I need a time to check improvements.

**Pull request closed without merging**
